### ISSUE TITLE
Missing Data in Readme

### ISSUE THREAD

**Issue by aneesh-joshi** [heyLinsir/BiMPM#1]
Thank you for the model

Please could you include:
1. Your models performance on different datasets (WikiQA, etc)
2. How to use your model

in the readme

**Comment by heyLinsir** [comment]
@aneesh-joshi 
Sorry about missing such information. But I didn't test this model on other datasets. Maybe I will do it in feature. 
About how to use. Actually, this model can't reach the performance given in the paper. Therefore I think it's better for you to use the code provided by the author of the paper. If you insist to use my code, I will add direction to readme.

**Comment by aneesh-joshi** [comment]
I am facing similar problems in reproducing results. I was hoping to find some working solution.
Thanks for your work and the reply.
What performance was your model able to achieve?
